### ISSUE TITLE
Error: Class 'p2made\demo\FlotDemoAsset' not found

### ISSUE THREAD

**Issue by alekciy** [p2made/yii2-sb-admin-theme#1]
https://github.com/p2made/yii2-sb-admin-theme/blob/master/views/sb-admin-2/site/index.php#L28

Maybe p2made\theme\sbAdmin\demo\FlotDemoAsset::register($this)? (in my install work).

**Comment by p2made** [comment]
I've been taking a break from coding, but am back on it now.
I shall make a priority of fixing this.

**Comment by p2made** [comment]
I've been taking a break from coding, but am back on it now.
I shall make a priority of fixing this.

**Comment by p2made** [comment]
Fixed

**Comment by Sahrun** [comment]
Installation failed, reverting ./composer.json to its original content.

                                                                        
  [UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"  
                                                                        

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
