### ISSUE TITLE
Metis Menu flicker on page load because active items read after document load

### ISSUE THREAD

**Issue by francislavoie** [p2made/yii2-sb-admin-theme#2]
This is quite a minor issue, but I managed to fix it myself so I decided I'd just drop this here to be added later on by the maintainer or by anyone else who runs into it. I made a custom Nav widget which extends the base one and adds the `collapse` CSS class if there are active items within the menu.

Drop the following code in your widget directory (or in this package's widget directory, changing the namespace) then include it in the navigation-left.php view with `use app\widgets\MetisNav as Nav;` or whatever your namespace is. Now, inactive collapsible menus won't render as uncollapsed first.

```
<?php

namespace app\widgets;

use Yii;
use yii\bootstrap\Nav;
use yii\helpers\Html;

class MetisNav extends Nav {

    /**
     * Customized widget for MetisMenu navigation dropdowns to not flicker on page load
     * by precomputing if the menu should be open or not. Portions were added below to
     * add the 'collapse' css class if there is an item active within the submenu.
     */
    public function renderItems() {
        $items = [];
        foreach ($this->items as $i => $item) {
            if (isset($item['visible']) && !$item['visible']) {
                continue;
            }
            $items[] = $this->renderItem($item);
        }

        // Begin custom code
        $hasActive = false;
        foreach ($this->items as $i => $child) {
            if($this->isItemActive($child)) {
                $hasActive = true;
                break;
            }
        }

        if(!$hasActive) {
            Html::addCssClass($this->options, 'collapse');
        }
        // End custom code

        return Html::tag('ul', implode("\n", $items), $this->options);
    }
}
```

Hope this is useful to someone.

Also @p2made I wanted to say thanks for making this extension, it saved me a good amount of time and definitely simplified implementing a sidebar menu.

**Comment by p2made** [comment]
Thanks for the feedback, & for your contribution.
I shall make a priority of implementing your fix.

**Comment by p2made** [comment]
I am going to be implementing this as I fix your other reported bug.

I've also recently discovered that Yii 2 has a sidebar menu, & shall be exploring how I can use that to improve this theme.

**Comment by p2made** [comment]
I've finally gotten to implementing this. Use `^1.6` as your version constraint. If you're also explicitly including `p2made/yii2-p2y2-things`, use `^1.16` as version constraint for that.
