### ISSUE TITLE
Class p2made\assets\BootstrapPluginAsset does not exist

### ISSUE THREAD

**Issue by francislavoie** [p2made/yii2-sb-admin-theme#3]
In SBAdmin2Asset, I think you meant to use `'p2made\assets\base\BootstrapPluginAsset',` instead (note `\base` appearing in the path). I had to make this modification for it to run since I updated.

**Comment by francislavoie** [comment]
Along the same lines, your lib requires `jquery.min.js` but the base YiiAsset requires `jquery.js` so I ended up with two copies, breaking all my JS on pages. That might just be something I need to fix on my end, but your JqueryAsset shouldn't also be loaded if `yii\web\JqueryAsset` is already loaded I think.

In this case to make it work for me, I just modified your `JqueryAsset` in `p2made\assets` to use `jquery.js` instead of the minified version so it would work for me, but both this and the above change would get wiped away in a future composer update unless they're rectified on your end.

If I'm wrong about these, let me know, it might be a configuration issue on my project side.

**Comment by p2made** [comment]
To the first... I've just done some major reworking of P2Y2Things, & not having updated yii2-sb-admin-theme, I've caused a break. I shall be onto it. In the meantime, use `p2made\assets\P2CoreLoaderAsset` & you will jave Jquery, Bootstrap (with plugin), & Font Awesome.

To the second... I use config file entries to nullify some of the Yii2 assets that P2Y2Things replace. I'll add that to the documentation as I fix the first.

For now, here is that mod from my `common/config/main.php`...

```
    'components' => [
        'assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null, 'js' => [],
                ],
                'yii\bootstrap\BootstrapAsset' => [
                    'sourcePath' => null, 'css' => [],
                ],
                'yii\bootstrap\BootstrapPluginAsset' => [
                    'sourcePath' => null, 'js' => [],
                ],
                'yii\jui\JuiAsset' => [
                    'sourcePath' => null, 'css' => [], 'js' => [],
                ],
                '\rmrevin\yii\fontawesome\AssetBundle' => [
                    'sourcePath' => null, 'css' => [],
                ],
            ],
        ],
        ...
    ],
```

**Comment by francislavoie** [comment]
Awesome, that did the trick!

Thanks again for the work on this extension, it's great :)

**Comment by p2made** [comment]
Thank you for the heads-up.

I hope you've noticed that with P2Y2Things you can have your assets load using the official CDNs with the latest (known) versions.

**Comment by p2made** [comment]
A little bit of tyding up the docs for P2Y2Things, to reflect recent changes, & I'm right onto fixing this.

**Comment by francislavoie** [comment]
Hm... Unfortunately, my dev environment was actually not reacting to updates at all, so after making those changed you recommended, it actually broke things but they just hadn't updated (damn rsync breaking...)

So... issues are still the same for me. Basically making those changes broke the order in which assets were loaded.

The following did fix my jQuery issue though, and removed the duplicated bootstrap js and css. So I guess overall the only issue I have now is that first one with the wrong path for BootstrapPluginAsset.

```
       'bundles' => [
            'yii\web\JqueryAsset' => [
                'js' => ['jquery.min.js'],
            ],
            'yii\bootstrap\BootstrapPluginAsset' => [
                'sourcePath' => null, 'js' => [],
            ],
            'yii\bootstrap\BootstrapAsset' => [
                'sourcePath' => null, 'css' => [],
            ],
        ],
```

**Comment by p2made** [comment]
I'm working on it right now, & as of this moment it works on my system. However you configure your Yii2, ensure that you're not loading any Yii2 assets that P2Y2Things duplicates. If you use the `P2CoreLoaderAsset`, you should have Jquery, Bootstrap (with plugin), & Font Awesome loaded in correct order. Under most circumstances you'd then load any other assets after `P2CoreLoaderAsset`.

**Comment by francislavoie** [comment]
Putting the following did the trick, but I still need to change the js property on `JqueryAsset` as above in my config otherwise it loads after `yii.js` and `yii.gridview.js` etc.

```
p2made\assets\P2CoreLoaderAsset::register($this);
p2made\theme\sbAdmin\assets\SBAdmin2Asset::register($this);
```

**Comment by p2made** [comment]
Yes, that should work. When I've uploaded my current work, `P2CoreLoaderAsset` will be loaded as a dependancy on `SBAdmin2Asset` so you only need to register the latter. Also, `P2CoreLoaderAsset` declares `yii\web\YiiAsset` as a dependancy, so there's no need to register that or anything which it loads.

**Comment by francislavoie** [comment]
Ran into another issue, Jui was loaded after Bootstrap, so the `.button()` function in on jQuery objects was the wrong one (for my code atleast) and broke my pages that used that to update the button loading state on ajax actions. I had to flip their order in the Asset.

**Comment by p2made** [comment]
I'll revise the loading order in `P2CoreLoaderAsset`.
