### ISSUE TITLE
Library broken

### ISSUE THREAD

**Issue by andrew-svirin** [p2made/yii2-sb-admin-theme#4]
v1.5.7

Hello, see on this error

Declaration of p2made\helpers\base\FontAwesome::s() should be compatible with rmrevin\yii\fontawesome\FontAwesome::s($options = Array)

**Comment by p2made** [comment]
My subclass doesn't declare or override rmrevin\yii\fontawesome\FontAwesome::s($options = Array). What it does do is provide a collection of methods that call it with various options preset.
