### ISSUE TITLE
Bootstrap conflicts with Yii2 default Bootstrap.js

### ISSUE THREAD

**Issue by wmkamerman** [p2made/yii2-sb-admin-theme#6]
Bootstrap.js is double initialized. To fix change the following file:

`/p2made/yii2-p2y2-things/assets/base/BootstrapPluginAsset.php`

Uncomment the `'js/bootstrap.min.js',` lines and add to **depends** the following line:
`'yii\bootstrap\BootstrapPluginAsset'`

Complete file:

	private $resourceData = array(
		'published' => [
			'sourcePath' => '@vendor/bower/bootstrap/dist',
			'js' => [
				//'js/bootstrap.min.js',
			],
		],
		'static' => [
			'baseUrl' => '//maxcdn.bootstrapcdn.com/bootstrap/',
			'js' => [
				//'js/bootstrap.min.js',
			],
		],
		'depends' => [
			'p2made\assets\JqueryAsset',
            'yii\bootstrap\BootstrapPluginAsset'
		],
	);

	public function init()
	{
		$this->resourceData['static']['baseUrl'] .= $this->version;

		$this->configureAsset($this->resourceData);
		parent::init();
	}

That's it. Now only the Yii bootstrap asset is used.

**Comment by p2made** [comment]
P2SB Admin Theme uses P2Y2Things which requires nullifying some Yii assets. That is described in the README of P2Y2Things but wasn't mentioned in the README for P2SB Admin Theme. I've added description of the nullifying to the READMEs for this & my other themes.

**Comment by wmkamerman** [comment]
Thanks!

**Comment by p2made** [comment]
I had been taking a break from my programming for health reasons. I am now back on the job 😀

**Comment by wmkamerman** [comment]
Awesome. You really did a terrific job!
