### ISSUE TITLE
Raphael Asset uses raphael-min.js instead of raphael.min.js

### ISSUE THREAD

**Issue by wmkamerman** [p2made/yii2-sb-admin-theme#7]
Raphael Asset uses `raphael-min.js` instead of `raphael.min.js`  and this causes errors. 

Edit file `/p2made/yii2-p2y2-things/assets/RaphaelAsset.php`

Then change the `published` resourceData to:

```
'published' => [
	'sourcePath' => '#/raphael-##-version-##',
	'js' => [
		'raphael.min.js',
	],
],
```

**Comment by p2made** [comment]
In some earlier versions Raphael did use the file name `raphael-min.js` & I missed the change. Fixed.

**Comment by wmkamerman** [comment]
No problem, glad to help!
